LOCAL_PATH := device/google/shamrock

$(call inherit-product, device/google/shamrock/device.mk)
$(call inherit-product, $(SRC_TARGET_DIR)/product/full_base_telephony.mk)

PRODUCT_DEVICE := shamrock
PRODUCT_NAME := fox_shamrock
PRODUCT_BRAND := Google
PRODUCT_MODEL := GM 5 Plus
PRODUCT_MANUFACTURER := Google

# TWRP Settings
TW_INCLUDE_CRYPTO := false
TWRP_INCLUDE_LOGCAT := true
TW_EXTRA_LANGUAGES := true
TW_HAS_EDL_MODE := true
#TW_USE_TOOLBOX := true
TW_THEME := portrait_hdpi
TW_INCLUDE_FUSE_EXFAT := true
TW_INCLUDE_FUSE_NTFS := true
TW_INCLUDE_NTFS_3G := true
TW_MAX_BRIGHTNESS := 255
TW_BRIGHTNESS_PATH := /sys/class/leds/lcd-backlight/brightness
TW_EXCLUDE_SUPERSU := true
TW_EXCLUDE_TWRPAPP := true
TW_SCREEN_BLANK_ON_BOOT := true
TW_HAS_NO_REAL_SDCARD := true
TW_INPUT_BLACK_LIST := "/dev/input/event1"
#TW_EXCLUDE_DEFAULT_USB_INIT := false
TW_CUSTOM_BATTERY_PATH := /sys/class/power_supply/battery
TW_INCLUDE_MTP := 1

# Maintainer Info
OF_MAINTAINER := Nobugger
FOX_DEVICE := shamrock
FOX_BUILD_TYPE := Unofficial
FOX_INTERNAL_RELEASE := R12.1
FOX_MANIFEST_VER := 12.1
FOX_OUT_NAME := OrangeFox-R12.1-Unofficial-shamrock

OF_SCREEN_H := 1920
OF_STATUS_BAR_HEIGHT := 60
OF_HIDE_NOTCH := 1
OF_FLASHLIGHT_ENABLE := 0
OF_USE_GREEN_LED := 0

# Shell & Core Tools
FOX_ALLOW_EARLY_SETTINGS_LOAD=1
FOX_BUILD_DEBUG_MESSAGES=0
FOX_ENABLE_APP_MANAGER=0
FOX_DELETE_AROMAFM=1
FOX_DELETE_INITD_ADDON=1
FOX_ASH_IS_BASH := 1
FOX_USE_BASH_SHELL := 1
FOX_USE_BUSYBOX_BINARY := 1
FOX_USE_DATE_BINARY := 1
FOX_USE_LZ4_BINARY := 1
FOX_USE_NANO_EDITOR := 1
FOX_USE_TAR_BINARY := 1
FOX_USE_XZ_UTILS := 1
FOX_USE_ZSTD_BINARY := 1
OF_USE_MAGISKBOOT := 1
OF_USE_MAGISKBOOT_FOR_ALL_PATCHES := 1
OF_INCLUDE_MAGISK := 1
FOX_VANILLA_BUILD=1
OF_CLOCK_POS := 2
OF_USE_LOCKSCREEN_BUTTON := 1
OF_USE_LEGACY_BATTERY_SERVICES := 1
OF_RUN_POST_FORMAT_PROCESS := 1
OF_PATCH_AVB20 := 1
#FOX_DELETE_AROMAFM := 1
#FOX_INSTALLER_DISABLE_AUTOREBOOT := 1