#!/system/bin/sh

while [ ! -f /sys/class/power_supply/usb/online ]; do
    sleep 0.1
done

chmod 0666 /sys/class/leds/green/trigger
echo battery-charging > /sys/class/leds/green/trigger
chmod 0444 /sys/class/leds/green/trigger

while true; do
    if [ $(cat /sys/class/power_supply/usb/online 2>/dev/null) -eq 1 ]; then
        # Kablo takılı -> trigger zaten battery-charging olduğu için LED yanar
        # Ama brightness'ı da kontrol et
        chmod 0666 /sys/class/leds/green/brightness
        echo 255 > /sys/class/leds/green/brightness
        chmod 0444 /sys/class/leds/green/brightness
    else
        # Kablo yok -> LED'i söndür
        chmod 0666 /sys/class/leds/green/brightness
        echo 0 > /sys/class/leds/green/brightness
        chmod 0444 /sys/class/leds/green/brightness
    fi
    sleep 1
done